### ISSUE TITLE
Enumeration mapping using name rather than int

### ISSUE THREAD

**Issue by siwatson** [otaviojava/Easy-Cassandra#36]
Is it possible to map an enumeration using its name rather than its integer ordinal?

**Comment by otaviojava** [comment]
Not yet.

**Comment by esheri3** [comment]
Are there any plans to do so? If so whats the timeline? If not, can you change the default behavior to make use of something besides the ordinal? Right now, anyone that re-orders the enum's in Java will inadvertently corrupt the mapping to the corresponding values in Cassandra since the ordinals will have changed. Can you default to make use of "toString()" or even "value()" on the enum for now?

**Comment by otaviojava** [comment]
I believe in next month.
